dtypes={'Age': 'float64',
       'Admissions': 'float64',
       'Clientid': 'float64',
       'Crisis': 'float64',
       'Diag_Anxiety, dissociative, stress-related, somatoform and other nonpsychotic mental disorders': 'float64',
       'Diag_Behavioral and emotional disorders with onset usually occurring in childhood and adolescence': 'float64',
       'Diag_Behavioral syndromes associated with physiological disturbances and physical factors': 'float64',
       'Diag_Disorders of adult personality and behavior': 'float64',
       'Diag_Intellectual disabilities': 'float64',
       'Diag_Mental and behavioral disorders due to psychoactive substance use': 'float64',
       'Diag_Mental disorders due to known physiological conditions': 'float64',
       'Diag_Mood (affective) disorders': 'float64',
       'Diag_No Diagnosis': 'float64',
       'Diag_Others': 'float64',
       'Diag_Pervasive and specific developmental disorders': 'float64',
       'Diag_Schizophrenia, schizotypal, delusional, and other non-mood psychotic disorders': 'float64',
       'HarmToOthers': 'float64',
       'HarmToProperty': 'float64',
       'IsMale': 'float64',
       'Pgm_A & D Adult Outpatient': 'float64',
       'Pgm_A & D Youth Day Tx': 'float64',
       'Pgm_A.T.I.- J.D.O.T.': 'float64',
       'Pgm_A.T.I.-C.O.R.E. Outpatient': 'float64',
       'Pgm_A.T.I.-C.O.R.E. Residential': 'float64',
       'Pgm_Acute Chldrns Extended Sv': 'float64',
       'Pgm_Adult Autism Center of Lifetime Learning': 'float64',
       'Pgm_Adult Centralized Eval': 'float64',
       'Pgm_Alliance House Apts': 'float64',
       'Pgm_Assertive Outreach Team': 'float64',
       'Pgm_Beacon Heights Elem Sch': 'float64',
       'Pgm_C.O.R.E.2 Outpatient': 'float64',
       'Pgm_C.O.R.E.2 Residential': 'float64',
       'Pgm_Carmen B Pingree Elementary School': 'float64',
       'Pgm_Carmen B Pingree In Home': 'float64',
       'Pgm_Carmen B Pingree Preschool': 'float64',
       'Pgm_Centralized Intake Clinic': 'float64',
       'Pgm_Childrens Outpatient Srvc': 'float64',
       'Pgm_Childrens Outpatient West': 'float64',
       'Pgm_Community Based Prov Ntwk': 'float64',
       'Pgm_Contract-Granite School District': 'float64',
       'Pgm_Contract-Jordan School District': 'float64',
       'Pgm_D.B.T. Day Tx Program': 'float64',
       'Pgm_Federal Forensics Grant': 'float64',
       'Pgm_Flexcare New Choices': 'float64',
       'Pgm_Forensic Unit': 'float64',
       'Pgm_Fresh Start/Recovery Prog': 'float64',
       'Pgm_H.S.S.C Am Fork': 'float64',
       'Pgm_H.S.S.C Highland': 'float64',
       'Pgm_H.S.S.C Riverton': 'float64',
       'Pgm_H.S.S.C. Boise': 'float64',
       'Pgm_H.S.S.C. Lab Services': 'float64',
       'Pgm_H.S.S.C. Layton': 'float64',
       'Pgm_H.S.S.C. Orem': 'float64',
       'Pgm_Homefront': 'float64',
       'Pgm_Independent Living': 'float64',
       'Pgm_Inpatient Hospital Summit Adult': 'float64',
       'Pgm_Inpatient Hospital Tooele Adult': 'float64',
       'Pgm_Inpatient Hospital Tooele Youth': 'float64',
       'Pgm_K.I.D.S': 'float64',
       'Pgm_Lab Services': 'float64',
       'Pgm_Masters Program': 'float64',
       'Pgm_Medical Records': 'float64',
       'Pgm_No Primary program': 'float64',
       'Pgm_North Valley Adult Pgm': 'float64',
       'Pgm_Pheasant Hollow': 'float64',
       'Pgm_Residential Tooele Youth': 'float64',
       'Pgm_Robert Frost Elem Sch': 'float64',
       'Pgm_S.R.S.': 'float64',
       'Pgm_Safe Haven 1': 'float64',
       'Pgm_Safe Haven 2': 'float64',
       'Pgm_School Based Program': 'float64',
       'Pgm_Summit County A & D': 'float64',
       'Pgm_Summit County Mental Hlth': 'float64',
       'Pgm_Summit JRI Jail': 'float64',
       'Pgm_Summit JRI Outpt': 'float64',
       'Pgm_Summit Jail': 'float64',
       'Pgm_Summit Prevention': 'float64',
       'Pgm_Summit School Contractor': 'float64',
       'Pgm_TMS': 'float64',
       'Pgm_Tooele After School Program': 'float64',
       'Pgm_Tooele County A & D': 'float64',
       'Pgm_Tooele County M. H.': 'float64',
       'Pgm_Tooele County Prevention': 'float64',
       'Pgm_Tooele Food Bank': 'float64',
       'Pgm_Tooele I-Wrap': 'float64',
       'Pgm_Tooele JRI Jail': 'float64',
       'Pgm_Tooele JRI Outpt': 'float64',
       'Pgm_Tooele Jail': 'float64',
       'Pgm_Tooele Resource Center': 'float64',
       'Pgm_Tooele Wendover': 'float64',
       'Pgm_Tooele Youth Services': 'float64',
       'Pgm_USH Summit Youth': 'float64',
       'Pgm_USH Tooele Adult': 'float64',
       'Pgm_Valley EPIC Bldg A': 'float64',
       'Pgm_Valley EPIC Bldg B': 'float64',
       'Pgm_Valley EPIC Bldg C': 'float64',
       'Pgm_Valley EPIC Bldg D': 'float64',
       'Pgm_Valley EPIC Outpatient Recovery Mngmnt': 'float64',
       'Pgm_Valley Plaza': 'float64',
       'Pgm_Valley Storefront': 'float64',
       'Pgm_Valley Woods': 'float64',
       'Pgm_ValleyAIM': 'float64',
       'Pgm_ValleyPhoenix': 'float64',
       'Pgm_ValleyWest': 'float64',
       'PosTest_6-Acetylmorphine': 'float64',
       'PosTest_7-Aminoclonazepam': 'float64',
       'PosTest_7-Hydroxyquetiapine': 'float64',
       'PosTest_9-hydroxyrisperidone': 'float64',
       'PosTest_ALT': 'float64',
       'PosTest_AST': 'float64',
       'PosTest_Albumin': 'float64',
       'PosTest_Alk Phos': 'float64',
       'PosTest_Alprazolam': 'float64',
       'PosTest_Amphetamine': 'float64',
       'PosTest_Amphetamines': 'float64',
       'PosTest_Anion Gap': 'float64',
       'PosTest_Aripiprazole': 'float64',
       'PosTest_BUN': 'float64',
       'PosTest_Barbiturates': 'float64',
       'PosTest_Basophil#': 'float64',
       'PosTest_Basophil%': 'float64',
       'PosTest_Benzodiazepines': 'float64',
       'PosTest_Benzoylecgonine': 'float64',
       'PosTest_Buprenorphine': 'float64',
       'PosTest_Bupropion': 'float64',
       'PosTest_Calcium': 'float64',
       'PosTest_Carisoprodol': 'float64',
       'PosTest_Chloride': 'float64',
       'PosTest_Cholesterol': 'float64',
       'PosTest_Clozapine': 'float64',
       'PosTest_Codeine': 'float64',
       'PosTest_Desmethylolanzapine': 'float64',
       'PosTest_Diazyme Potassium': 'float64',
       'PosTest_Diazyme Sodium': 'float64',
       'PosTest_EDDP': 'float64',
       'PosTest_EGFR (African American)': 'float64',
       'PosTest_EGFR (Non-African American)': 'float64',
       'PosTest_Eosinophil#': 'float64',
       'PosTest_Eosinophil%': 'float64',
       'PosTest_EtG': 'float64',
       'PosTest_EtS': 'float64',
       'PosTest_Ethyl Alcohol (mg/dL)': 'float64',
       'PosTest_Fentanyl': 'float64',
       'PosTest_Gabapentin': 'float64',
       'PosTest_Glucose': 'float64',
       'PosTest_HCT': 'float64',
       'PosTest_HDL ': 'float64',
       'PosTest_HGB': 'float64',
       'PosTest_Haloperidol': 'float64',
       'PosTest_HbA1c': 'float64',
       'PosTest_Hydrocodone': 'float64',
       'PosTest_Hydromorphone': 'float64',
       'PosTest_Hydroxybupropion': 'float64',
       'PosTest_LDL Direct': 'float64',
       'PosTest_LDL/HDL Ratio': 'float64',
       'PosTest_Lorazepam': 'float64',
       'PosTest_Lymphocyte#': 'float64',
       'PosTest_Lymphocyte%': 'float64',
       'PosTest_MCH': 'float64',
       'PosTest_MCHC': 'float64',
       'PosTest_MCV': 'float64',
       'PosTest_MDA': 'float64',
       'PosTest_MDEA': 'float64',
       'PosTest_MDMA': 'float64',
       'PosTest_MPV': 'float64',
       'PosTest_Meprobamate': 'float64',
       'PosTest_Methadone': 'float64',
       'PosTest_Methamphetamine': 'float64',
       'PosTest_Mitragynine': 'float64',
       'PosTest_Monocyte#': 'float64',
       'PosTest_Monocyte%': 'float64',
       'PosTest_Morphine': 'float64',
       'PosTest_N-Desmethyclozapine': 'float64',
       'PosTest_Neutrophil#': 'float64',
       'PosTest_Neutrophil%': 'float64',
       'PosTest_Norbuprenorphine': 'float64',
       'PosTest_Nordiazepam': 'float64',
       'PosTest_Norfentanyl': 'float64',
       'PosTest_Norhydrocodone': 'float64',
       'PosTest_Noroxycodone': 'float64',
       'PosTest_O-desmethyltramadol': 'float64',
       'PosTest_Olanzapine': 'float64',
       'PosTest_Oxazepam': 'float64',
       'PosTest_Oxycodone': 'float64',
       'PosTest_Oxymorphone': 'float64',
       'PosTest_PLT': 'float64',
       'PosTest_Potassium': 'float64',
       'PosTest_Pregabalin': 'float64',
       'PosTest_Protein': 'float64',
       'PosTest_Quetiapine': 'float64',
       'PosTest_RBC': 'float64',
       'PosTest_RDW-CV': 'float64',
       'PosTest_Risperidone': 'float64',
       'PosTest_Ritalinic Acid': 'float64',
       'PosTest_THC-COOH': 'float64',
       'PosTest_TSH': 'float64',
       'PosTest_Temazepam': 'float64',
       'PosTest_Total Bilirubin': 'float64',
       'PosTest_Total CO2': 'float64',
       'PosTest_Tramadol': 'float64',
       'PosTest_Triglycerides': 'float64',
       'PosTest_UR-144 5-Pentanoic acid metabolite': 'float64',
       'PosTest_VLDL': 'float64',
       'PosTest_WBC': 'float64',
       'PosTest_Ziprasidone': 'float64',
       'PosTest_aOH-Alprazolam': 'float64',
       'SelfHarm': 'float64'}